


CREATE TABLE DimCustomer(CustomerKey BIGINT, GeographyKey BIGINT, CustomerAlternateKey VARCHAR, Title VARCHAR, FirstName VARCHAR, MiddleName VARCHAR, LastName VARCHAR, NameStyle BOOLEAN, BirthDate BIGINT, MaritalStatus VARCHAR, Suffix VARCHAR, Gender VARCHAR, EmailAddress VARCHAR, YearlyIncome BIGINT, TotalChildren BIGINT, NumberChildrenAtHome BIGINT, EnglishEducation VARCHAR, SpanishEducation VARCHAR, FrenchEducation VARCHAR, EnglishOccupation VARCHAR, SpanishOccupation VARCHAR, FrenchOccupation VARCHAR, HouseOwnerFlag BIGINT, NumberCarsOwned BIGINT, AddressLine1 VARCHAR, AddressLine2 VARCHAR, Phone VARCHAR, DateFirstPurchase BIGINT, CommuteDistance VARCHAR);
CREATE TABLE DimDate(DateKey BIGINT, FullDateAlternateKey BIGINT, DayNumberOfWeek BIGINT, EnglishDayNameOfWeek VARCHAR, SpanishDayNameOfWeek VARCHAR, FrenchDayNameOfWeek VARCHAR, DayNumberOfMonth BIGINT, DayNumberOfYear BIGINT, WeekNumberOfYear BIGINT, EnglishMonthName VARCHAR, SpanishMonthName VARCHAR, FrenchMonthName VARCHAR, MonthNumberOfYear BIGINT, CalendarQuarter BIGINT, CalendarYear BIGINT, CalendarSemester BIGINT, FiscalQuarter BIGINT, FiscalYear BIGINT, FiscalSemester BIGINT);
CREATE TABLE DimGeography(GeographyKey BIGINT, City VARCHAR, StateProvinceCode VARCHAR, StateProvinceName VARCHAR, CountryRegionCode VARCHAR, EnglishCountryRegionName VARCHAR, SpanishCountryRegionName VARCHAR, FrenchCountryRegionName VARCHAR, PostalCode VARCHAR, SalesTerritoryKey BIGINT, IpAddressLocator VARCHAR);
CREATE TABLE DimProduct(ProductKey BIGINT, ProductAlternateKey VARCHAR, ProductSubcategoryKey BIGINT, WeightUnitMeasureCode VARCHAR, SizeUnitMeasureCode VARCHAR, EnglishProductName VARCHAR, SpanishProductName VARCHAR, FrenchProductName VARCHAR, StandardCost DOUBLE, FinishedGoodsFlag BOOLEAN, Color VARCHAR, SafetyStockLevel BIGINT, ReorderPoint BIGINT, ListPrice DOUBLE, Size VARCHAR, SizeRange VARCHAR, Weight DOUBLE, DaysToManufacture BIGINT, ProductLine VARCHAR, DealerPrice DOUBLE, "Class" VARCHAR, Style VARCHAR, ModelName VARCHAR, LargePhoto VARCHAR, EnglishDescription VARCHAR, FrenchDescription VARCHAR, ChineseDescription VARCHAR, ArabicDescription VARCHAR, HebrewDescription VARCHAR, ThaiDescription VARCHAR, GermanDescription VARCHAR, JapaneseDescription VARCHAR, TurkishDescription VARCHAR, StartDate BIGINT, EndDate BIGINT, Status VARCHAR);
CREATE TABLE DimSalesTerritory(SalesTerritoryKey BIGINT, SalesTerritoryAlternateKey BIGINT, SalesTerritoryRegion VARCHAR, SalesTerritoryCountry VARCHAR, SalesTerritoryGroup VARCHAR, SalesTerritoryImage VARCHAR);
CREATE TABLE FactInternetSales(ProductKey BIGINT, OrderDateKey BIGINT, DueDateKey BIGINT, ShipDateKey BIGINT, CustomerKey BIGINT, PromotionKey BIGINT, CurrencyKey BIGINT, SalesTerritoryKey BIGINT, SalesOrderNumber VARCHAR, SalesOrderLineNumber BIGINT, RevisionNumber BIGINT, OrderQuantity BIGINT, UnitPrice DOUBLE, ExtendedAmount DOUBLE, UnitPriceDiscountPct BIGINT, DiscountAmount BIGINT, ProductStandardCost DOUBLE, TotalProductCost DOUBLE, SalesAmount DOUBLE, TaxAmt DOUBLE, Freight DOUBLE, CarrierTrackingNumber VARCHAR, CustomerPONumber VARCHAR, OrderDate BIGINT, DueDate BIGINT, ShipDate BIGINT);




